//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.06 at 01:56:24 AM UTC 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.ensa.ma/MySoapService", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ma.ensa.mysoapservice;
